---
apt_repos_filename: ansible_managed

repositories_list:
  - deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
  - deb http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  - deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
  - deb http://archive.ubuntu.com/ubuntu/ jammy-proposed main restricted universe multiverse
  - deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
