---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
  - package-ecosystem: "pip"
    directory: "/devenv/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-update"
