---
- name: Install packages
  ansible.builtin.apt:
    pkg:
      - atop
      - bash-completion
      - bind9-host
      - ca-certificates
      - command-not-found
      - cron
      - curl
      - dnsutils
      - ethtool
      - hping3
      - htop
      - httpie
      - iftop
      - iotop
      - iperf3
      - iputils-arping
      - iputils-ping
      - iputils-tracepath
      - jq
      - lsb-release
      - lshw
      - lsof
      - ltrace
      - mtr-tiny
      - nano
      - net-tools
      - netcat-openbsd
      - nload
      - nmap
      - pciutils
      - pigz
      - pv
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - rsync
      - screen
      - software-properties-common
      - strace
      - sysstat
      - tcpdump
      - telnet
      - tmux
      - traceroute
      - unzip
      - vim
      - wget
      - whois
      - zip
    install_recommends: false
    state: present
    update_cache: true

- name: Remove packages
  ansible.builtin.apt:
    pkg:
      - cloud-init
      - fwupd
      - open-vm-tools
      - snapd
      - vim-tiny
    state: absent
    autoclean: true
    autoremove: true
